<?php /*  $Id: dl_templatevars.phtml 25 2010-03-24 20:34:24Z stefan $ */ ?>
<p id="plugin-tt-note">Use<span class="sort"> </span>to sort/move the TVs</p>
<dl id="plugin-tt-tmplvars">
<?php foreach( $categories as $category ): ?>
    <dt><?php echo $category['category']; ?></dt>
    <dd>
        <ul class="category_elements" id="category-<?php echo $category['id']; ?>">
        <?php foreach( $category['elements'] as $tmplvar ): ?>
            <li<?php echo $tmplvar['assigned'] ? ' class="checked"' :''?>>
                <?php if( $tmplvar['locked'] === '1' && $_SESSION['mgrRole'] !== '1' ): ?>

                    <input type="checkbox"<?php echo $tmplvar['assigned'] ? ' checked="checked"' : ''?> id="tmplvar-<?php echo $tmplvar['id']; ?>" name="plugin[tt][tplvars][id][]" value="<?php echo $tmplvar['id']; ?>" />
                    <?php echo $tmplvar['name']; ?> <em>(<?php echo $_lang['locked']; ?>)</em>

                <?php else: ?>

                    <span class="sort-elements-category-<?php echo $category['id']; ?> sort"></span>
                    <label for="tmplvar-<?php echo $tmplvar['id']; ?>">
                        <span class="name"><?php echo $tmplvar['name']; ?></span>
                        <?php if( $tmplvar['caption'] !==  $tmplvar['name'] ) : ?><span class="description">- <?php echo $tmplvar['caption']; ?></span><?php endif; ?>
                    </label>
                    <input type="checkbox"<?php echo $tmplvar['assigned'] ? ' checked="checked"' : ''?> id="tmplvar-<?php echo $tmplvar['id']; ?>" name="plugin[tt][tplvars][id][]" value="<?php echo $tmplvar['id']; ?>" />
                    <input type="text" class="rank" id="tmplvar-<?php echo $tmplvar['id']; ?>-rank" name="plugin[tt][tplvars][rank][<?php echo $tmplvar['id']; ?>]" value="" />

                <?php endif; ?>

            </li>
        <?php endforeach; ?>
        </ul>
    </dd>
<?php endforeach; ?>
</dl>
