<?php /* $Id: ontempformprerender.phtml 25 2010-03-24 20:34:24Z stefan $ */ ?>

<link rel="stylesheet" type="text/css" href="<?php echo $_plugin_params['rel_path']; ?>skin/css/tvs_on_template.css" />
<script type="text/javascript" src="media/script/tabpane.js"></script>
<script type="text/javascript" src="<?php echo $_plugin_params['rel_path']; ?>skin/js/tvs_on_template.js"></script>
<script type="text/javascript">

window.addEvent('domready', function() {

    var _plugin_tt = new Tvs_On_Template({
        action           : <?php echo (int)$modx->manager->action; ?>,
        templates        : [<?php echo $templates_arraystring; ?>],
        input_template   : $E('input[name=templatename]'),
        current_template : $E('input[name=templatename]').getProperty('value'),
        tv_container     : 'plugin-tt-tmplvars',
        savebutton       : $E('li#Button1 a'),
        template_effect  : new Fx.Styles( $E('input[name=templatename]'), {
                               duration   : 800,
                               transition : Fx.Transitions.Quad.easeOut
                           }),
        icons            : {
                               ok        : '<?php echo $_plugin_params['rel_path']; ?>skin/img/ok.png',
                               ok_gif    : '<?php echo $_plugin_params['rel_path']; ?>skin/img/ok.gif',
                               error     : '<?php echo $_plugin_params['rel_path']; ?>skin/img/error.png',
                               error_gif : '<?php echo $_plugin_params['rel_path']; ?>skin/img/error.gif',
                               sort      : '<?php echo $_plugin_params['rel_path']; ?>skin/img/sort.png',
                               sort_gif  : '<?php echo $_plugin_params['rel_path']; ?>skin/img/sort.gif'
                           }
    });

    // http://www.mediacollege.com/internet/javascript/form/disable-return.html
    function _plugin_stopRKey(e) {
        if( _plugin_tt.status === false ) {
            var e = (e) ? e : ((event) ? event : null);
            var node = (e.target) ? e.target : ((e.srcElement) ? e.srcElement : null);
            if( ( e.keyCode === 13 ) && ( node.type === 'text' ) ) {
                _plugin_tt.options.template_effect.start({
                    'background-color' : ['#F66', '#FFF']
                });
                return false;
            }
        }
    }
    document.onkeypress = _plugin_stopRKey;

    if( window.ie6 ) {
        /**
         * Fixes for ie6
         * 
         * # hover for label
         * # ie doesn't change the status of a checkbox if it has the style visibility:hidden
         * # add savebutton functionality
         * 
         */
        $$('dl#plugin-tt-tmplvars ul.category_elements').each(function( ul ) {
            ul.getElements('label').each(function(label){
                label.getPrevious().adopt( new Element('img',{src:"<?php echo $_plugin_params['rel_path']; ?>skin/img/sort.gif"}));
                label.addEvents({
                    'mouseenter' : function() {
                        this.setStyles({
                            'background-color' : '#88939E', 
                            'color'            : '#fff' 
                        });
                    },
                    'mouseleave' : function() {
                        this.setStyles({
                            'background-color' : 'transparent', 
                            'color'            : '#000' 
                        });
                    },
                    'click' : function() {
                        if( this.getNext().getProperty('checked') === true ) {
                            this.getNext().removeProperty('checked');
                            this.getParent().removeClass('checked');
                        }
                        else {
                            this.getNext().setProperty( 'checked' , 'checked' );
                            this.getParent().addClass( 'checked' );
                        }
                    }
                });
            });
        });
        
        $E('li#Button1 a').addEvent('click',function(){
            if (_plugin_tt.status === true) {
                documentDirty = false;
                document.mutate.save.click();
                saveWait('mutate');
            }
        });
    }
});
</script>
